application: platinum-tube-128803
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# Handlers define how to route requests to your application.
handlers:
- url: /js
  static_dir: js
  application_readable: true
- url: /fonts
  static_dir: fonts
  application_readable: true
- url: /css
  static_dir: css
  application_readable: true
- url: /templates
  static_dir: templates
  application_readable: true
- url: /images
  static_dir: images

- url: .*
  script: main.app 

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
- name: ssl
  version: latest